services:
  postgres:
    container_name: postgres-sql-wro
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: whatsapp_ripoff
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - whatsapp-ripoff
    restart: unless-stopped
  keycloak:
    container_name: keycloak-wro
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - whatsapp-ripoff
    command:
      - "start-dev"

networks:
  whatsapp-ripoff:
    driver: bridge

volumes:
    postgres:
      driver: local

